// The verbs live in ONE generated file, rendered from the verb registry and
// the loaded constitution; the hand-written skill names none of them
// (docs/cli.md §brief).
//
// The brief is generated per install, gitignored, and regenerated by `init` and
// `skills update`. That is the whole point: a tracked brief goes stale on a
// content commit, and a hand-written verb list goes stale on an engine commit —
// which is exactly how 8 of 16 verbs came to appear in no skill at all.
import { createHash } from "node:crypto";
import {
  buildNameIndex,
  codeUnitCompare,
  type EffectiveVocabulary,
  type FlattenedRegistry,
  observeVocabulary,
  type PageInput,
  passRows,
  vocabularyNames,
} from "@wikiwright/core";
import { lintOptionsFor, type VaultOk } from "./law.ts";
import { type CommandSpec, flagsOf, ROLE_RANK, type Role } from "./spec.ts";

/** Vault-relative; gitignored, like `freshness.json`. */
export const BRIEF_PATH = "generated/BRIEF.md";

/**
 * docs/cli.md §brief: the WORKFLOW slot each role verb fills. The reverse
 * gate reads this map — a role verb with no slot fails `skills.test.ts`, so "the
 * brief renders every verb" is a tautology plus a guard rather than a promise.
 */
export const WORKFLOW_SLOTS: Readonly<Record<string, string>> = {
  brief: "once per session: read this file",
  search: "before creating anything: search both scripts",
  type: "before writing: read the contract you are about to satisfy",
  vocabulary: "when a category or label is in doubt: read what the vocabulary admits",
  graph: "coverage, derived: the edges a label carries, and the pages on one side that carry none",
  write:
    "the write itself: Markdown in, one page out — or a directory of drafts landed together — judged before a byte lands",
  new: "a page that does not exist yet: the skeleton write",
  lint: "a draft, before it lands",
  check: "the whole vault, and the generated artifacts",
  fix: "a finding that carries a `fix`: run its argv",
  // The consumer verbs a writer also renders: each still answers one question,
  // and a verb in the brief with no slot is a verb nobody knows when to run.
  schema: "the whole generated registry, when a flag is in doubt",
  version: "which engine build is answering",
  okf: "the interop conformance check, when a bundle claims the profile",
};

function verbLine(spec: CommandSpec): string[] {
  const flags = flagsOf(spec)
    .map((f) => (f.type === "string" ? `--${f.name} <v>` : `--${f.name}`))
    .join(" ");
  const positionals = spec.positionals
    .map((p) => (p.required ? `<${p.name}>` : `[${p.name}]`))
    .join(" ");
  const subcommands =
    spec.subcommands === undefined ? "" : ` — subcommands: ${spec.subcommands.join(", ")}`;
  return [
    `### \`${spec.name}\` — ${WORKFLOW_SLOTS[spec.name] ?? spec.summary}`,
    "",
    `\`wikiwright ${spec.name}${positionals === "" ? "" : ` ${positionals}`}\`${subcommands}${flags === "" ? "" : ` — flags: ${flags}`}`,
    "",
    ...(spec.examples[0] === undefined ? [] : ["```text", spec.examples[0], "```", ""]),
  ];
}

/**
 * One declared vocabulary, as a writer needs it: every entry with the
 * properties its module declared for it, rendered as the module wrote them.
 * What a property MEANS is the module's to say, in its skill fragment below;
 * the brief renders none of it.
 */
function declaredLines(vocabulary: EffectiveVocabulary): string[] {
  const entries = [...vocabulary.entries.values()].sort((a, b) => codeUnitCompare(a.name, b.name));
  if (entries.length === 0)
    return [`No \`${vocabulary.name}\` entry is declared (${vocabulary.mode}).`];
  return entries.map((entry) => {
    const properties = Object.entries(entry.properties)
      .sort(([a], [b]) => codeUnitCompare(a, b))
      .map(([key, value]) => `${key}: ${JSON.stringify(value)}`);
    const status = entry.status === "retired" ? " (retired)" : "";
    return `- \`${entry.name}\`${status}${properties.length === 0 ? "" : ` — ${properties.join(", ")}`}`;
  });
}

/** The head of one vocabulary's census — its values, most used first (docs/concepts.md §Generated artifacts). */
function observedLines(
  name: string,
  observed: readonly { label: string; count: number }[],
): string[] {
  if (observed.length === 0) return [`No \`${name}\` value has been observed in this vault yet.`];
  return [
    observed
      .slice(0, 20)
      .map((row) => `\`${row.label}\` (${row.count})`)
      .join(" · "),
  ];
}

export interface BriefInput {
  role: Role;
  /**
   * The registry, PASSED rather than imported: `commands.ts` imports the brief
   * verb, so importing it back here is a cycle whose top-level constants read
   * `undefined` under ESM. The caller has the array; handing it over costs one
   * parameter and removes the cycle entirely.
   */
  commands: readonly CommandSpec[];
  registry: FlattenedRegistry;
  /**
   * docs/extending.md §What a module registers: the skill fragments the loaded
   * modules contributed. A kit's grammar is law an agent has to write under, and
   * a brief that did not say so would leave the agent to infer it from findings.
   */
  moduleSkills?: readonly { module: string; heading: string; body: string }[];
  /**
   * docs/constitution.md §Vocabularies: the census of every REGISTERED vocabulary, computed by the
   * caller's one parser pass — a kit's vocabulary is a vocabulary here too.
   */
  observed: Readonly<Record<string, readonly { label: string; count: number }[]>>;
  /** `engine.json`'s digest, so a brief can be told from the law it was cut from. */
  constitutionDigest: string;
}

/**
 * docs/cli.md §brief: the modules' own paragraphs, in load order
 * and under the module that contributed each. Byte-reproducible like the rest of
 * the brief: the order is the registry's, and the registry's order is the
 * bundle's declaration order.
 */
function moduleSkillLines(
  fragments: readonly { module: string; heading: string; body: string }[],
): string[] {
  if (fragments.length === 0) return [];
  const out: string[] = ["## What the loaded modules add", ""];
  for (const fragment of fragments) {
    out.push(`### ${fragment.heading} (\`${fragment.module}\`)`, "", fragment.body, "");
  }
  return out;
}

/**
 * docs/cli.md §skills Byte-reproducible from the registry and the census:
 * no clock, no absolute path, no counts that change on a content commit except
 * the census block, which is why the LIVE counts live in `type show --brief`.
 */
export function renderBrief(input: BriefInput): string {
  const { role, registry } = input;
  const rank = ROLE_RANK[role];
  const verbs = input.commands
    .filter((c) => ROLE_RANK[c.role] <= rank)
    .sort((a, b) => codeUnitCompare(a.name, b.name));
  const types = [...registry.types.values()]
    .filter((t) => t.abstract !== true && t.status === "active")
    .sort((a, b) => codeUnitCompare(a.name, b.name));
  const reserved = ["claude", "agents", "readme", "skill", "index", "log"];
  // The table this bundle is judged under: the kernel's rows plus every arm
  // and check a loaded module registered, so the count is this vault's.
  const rows = passRows(registry.modules);
  const fixRouted = rows.filter((r) => r.fixer !== undefined).length;
  const vocabularies = [...registry.vocabularies.values()].sort((a, b) =>
    codeUnitCompare(a.name, b.name),
  );

  return [
    `# wikiwright — the ${role}'s brief`,
    "",
    "Generated by `wikiwright brief`. Do not edit: it is regenerated per install,",
    "and the judgment that is not in it lives in the hand-written skill beside it.",
    "",
    `Constitution digest: \`${input.constitutionDigest}\``,
    "",
    "## The loop",
    "",
    "1. `search` every name form, in both scripts, before you create anything.",
    "2. `type show <type> --brief` — the contract, with live counts.",
    "3. Draft the Markdown, then `write <path> --dry-run` and read the findings.",
    "4. `write` for real; the engine stamps the dates and writes the History line.",
    "5. Commit. The gate runs the same judge over what the commit would contain.",
    "",
    "## Findings",
    "",
    "If a finding has `fix`, run its `argv` (fill any placeholders first). If it has",
    "`queue`, it is not yours — continue. A queued finding on a line you did not write",
    "is a warning, not a block.",
    "",
    `Of ${rows.length} passes, ${fixRouted} name a fixer; the rest are queues or census rows.`,
    "",
    "One sentence on search: not-found is only as good as the coverage block. Never",
    "claim absence while `caps.hit` is true — the cap cut the list before the end.",
    "",
    "## Verbs",
    "",
    ...verbs.flatMap(verbLine),
    "## Types",
    "",
    ...types.map(
      (t) => `- \`${t.name}\` — ${t.use_when ?? t.description ?? "no use_when declared"}`,
    ),
    "",
    "## Vocabularies, as declared",
    "",
    ...vocabularies.flatMap((v) => [`### \`${v.name}\` (${v.mode})`, "", ...declaredLines(v), ""]),
    "## Vocabularies, as this vault uses them",
    "",
    ...Object.entries(input.observed)
      .sort(([a], [b]) => codeUnitCompare(a, b))
      .flatMap(([name, rows]) => [`### \`${name}\``, "", ...observedLines(name, rows), ""]),
    ...moduleSkillLines(input.moduleSkills ?? []),
    "## Names",
    "",
    `Reserved basenames: ${reserved.map((r) => `\`${r}\``).join(", ")}.`,
    "",
    "A wikilink resolves to a canonical basename, never to an alias: write",
    "`[[Canonical|what you meant]]`. A page whose title is not Latin carries a Latin",
    "alias, so both scripts find it.",
    "",
  ].join("\n");
}

/** The constitution digest the brief prints, computed here rather than through the Writer. */
const sha256 = (text: string): string => createHash("sha256").update(text, "utf8").digest("hex");

/**
 * The brief for a loaded law over a given page set. `briefFor` reads both off
 * the disk; `init` hands it the vault as it will stand AFTER the copy, so the
 * plan can say whether the installed brief would change (docs/cli.md §The dry-run law).
 */
export function briefOf(
  vault: VaultOk,
  pages: PageInput[],
  role: Role,
  commands: readonly CommandSpec[],
): string {
  const options = lintOptionsFor(vault, buildNameIndex(pages));
  // docs/constitution.md §Vocabularies: every vocabulary the loaded modules register,
  // never a literal name — a kit's vocabulary is a vocabulary here too.
  const observed = Object.fromEntries(
    vocabularyNames(vault.modules).map((name) => [
      name,
      observeVocabulary(name, pages, vault.registry, options).map((row) => ({
        label: row.label,
        count: row.count,
      })),
    ]),
  );
  return renderBrief({
    role,
    commands,
    registry: vault.registry,
    moduleSkills: vault.modules.skills,
    observed,
    constitutionDigest: sha256(JSON.stringify([...vault.registry.types.keys()].sort())).slice(
      0,
      12,
    ),
  });
}
