// The verbs live in ONE generated file, rendered from the verb registry and
// the loaded constitution; the hand-written skill names none of them
// (docs/cli.md §brief).
//
// The brief is generated per install, gitignored, and regenerated by `init` and
// `skills update`. That is the whole point: a tracked brief goes stale on a
// content commit, and a hand-written verb list goes stale on an engine commit —
// which is exactly how 8 of 16 verbs came to appear in no skill at all.
import {
  buildNameIndex,
  codeUnitCompare,
  type EffectiveVocabulary,
  type FlattenedRegistry,
  observeVocabulary,
  type PageInput,
  passRows,
  vocabularyNames,
} from "@wikiwright/core";
import { lawDigest } from "./bundle.ts";
import { lintOptionsFor, type VaultOk } from "./law.ts";
import { markerAt } from "./marker.ts";
import { type CommandSpec, flagsOf, ROLE_RANK, type Role } from "./spec.ts";

/** Vault-relative; gitignored, like `freshness.json`. */
export const BRIEF_PATH = "generated/BRIEF.md";

/**
 * docs/cli.md §brief: the WORKFLOW slot each role verb fills. The reverse
 * gate reads this map — a role verb with no slot fails `skills.test.ts`, so "the
 * brief renders every verb" is a tautology plus a guard rather than a promise.
 */
export const WORKFLOW_SLOTS: Readonly<Record<string, string>> = {
  brief: "once per session: read this file",
  read: "a page by path, name, alias or title — the sections a task needs, with its digest, under a budget; never `find` or `rg` for a path",
  search:
    "before creating anything: search both scripts; `--type <t>` alone lists a type's pages; results carry `band` and `match_reasons`; `--items` for the claims and relations themselves; `--files` for every page that mentions a term",
  type: "before writing: read the contract you are about to satisfy",
  vocabulary: "when a category or label is in doubt: read what the vocabulary admits",
  graph: "coverage, derived: the edges a label carries, and the pages on one side that carry none",
  write:
    "the write itself: Markdown in, one page out — or a directory of drafts landed together — judged before a byte lands; the page arrives on stdin",
  new: "a page that does not exist yet: the skeleton write",
  lint: "a draft, before it lands",
  check: "the whole vault, and the generated artifacts",
  fix: "a finding that carries a `fix`: run its argv",
  // The consumer verbs a writer also renders: each still answers one question,
  // and a verb in the brief with no slot is a verb nobody knows when to run.
  schema: "the whole generated registry, when a flag is in doubt",
  version: "which engine build is answering",
  okf: "the interop conformance check, when a bundle claims the profile",
};

function verbLine(spec: CommandSpec): string[] {
  const flags = flagsOf(spec)
    .map((f) => (f.type === "string" ? `--${f.name} <v>` : `--${f.name}`))
    .join(" ");
  const positionals = spec.positionals
    .map((p) => (p.required ? `<${p.name}>` : `[${p.name}]`))
    .join(" ");
  const subcommands =
    spec.subcommands === undefined ? "" : ` — subcommands: ${spec.subcommands.join(", ")}`;
  return [
    `### \`${spec.name}\` — ${WORKFLOW_SLOTS[spec.name] ?? spec.summary}`,
    "",
    `\`wikiwright ${spec.name}${positionals === "" ? "" : ` ${positionals}`}\`${subcommands}${flags === "" ? "" : ` — flags: ${flags}`}`,
    "",
    ...(spec.examples[0] === undefined ? [] : ["```text", spec.examples[0], "```", ""]),
  ];
}

/**
 * One declared vocabulary, as a writer needs it: every entry with the
 * properties its module declared for it, rendered as the module wrote them.
 * What a property MEANS is the module's to say, in its skill fragment below;
 * the brief renders none of it.
 */
function declaredLines(vocabulary: EffectiveVocabulary): string[] {
  const entries = [...vocabulary.entries.values()].sort((a, b) => codeUnitCompare(a.name, b.name));
  if (entries.length === 0)
    return [`No \`${vocabulary.name}\` entry is declared (${vocabulary.mode}).`];
  return entries.map((entry) => {
    const properties = Object.entries(entry.properties)
      .sort(([a], [b]) => codeUnitCompare(a, b))
      .map(([key, value]) => `${key}: ${JSON.stringify(value)}`);
    const status = entry.status === "retired" ? " (retired)" : "";
    return `- \`${entry.name}\`${status}${properties.length === 0 ? "" : ` — ${properties.join(", ")}`}`;
  });
}

/** The head of one vocabulary's census — its values, most used first (docs/concepts.md §Generated artifacts). */
function observedLines(
  name: string,
  observed: readonly { label: string; count: number }[],
): string[] {
  if (observed.length === 0) return [`No \`${name}\` value has been observed in this vault yet.`];
  return [
    observed
      .slice(0, 20)
      .map((row) => `\`${row.label}\` (${row.count})`)
      .join(" · "),
  ];
}

/**
 * docs/cli.md §brief: the writer's loop, the steps from a name to a landed page.
 * The maintainer's extends it, so the two cannot drift apart.
 */
const WRITER_LOOP: readonly string[] = [
  "1. `search` every name form, in both scripts, before you create anything.",
  "2. `type show <type> --brief` — the contract, with live counts.",
  "3. Draft the Markdown, then `write <path> --dry-run` and read the findings.",
  "4. `write` for real; the engine stamps the dates and writes the History line.",
  "5. Commit. The gate runs the same judge over what the commit would contain.",
];

/**
 * docs/cli.md §brief: the line every role's loop opens with. A session reaches
 * for its own tools to look — reading lines with context, listing, counting,
 * querying the generated artifacts — and should; what the engine holds and the
 * files do not is the law, identity, a judged write and a version to cite.
 */
const PRINCIPLE =
  "Use the engine to decide, to write and to attribute; use your own tools to look.";

/**
 * docs/cli.md §brief: "The loop", one per role, each opening on the principle.
 * The consumer's names no verb: its `## Verbs` section renders the only ones it
 * may run, and a loop that named another would hand a reader a step the binary
 * refuses.
 */
const LOOPS: Readonly<Record<Role, readonly string[]>> = {
  consumer: [
    PRINCIPLE,
    "1. Select the bundle first, and pass its root explicitly with `--root` on every command.",
    "2. Search every name form, in both scripts, before you say a thing is absent; read the coverage block.",
    "3. Read the sections the task needs. Keep each answer's `metadata.bundle`, and a page's digest where the answer carries one, beside what you took from it; keep a qualification with the claim it qualifies.",
    "4. Hand a child the passages it needs verbatim, with their bundle, path and digest, and addresses for the rest; never an alias.",
    "5. Report a knowledge problem as a proposal to the bundle's feedback destination or to your caller, never by editing a copy you were given to read.",
  ],
  writer: [PRINCIPLE, ...WRITER_LOOP],
  maintainer: [
    PRINCIPLE,
    ...WRITER_LOOP,
    "6. A finding with `queue` is a judgment: adjudicate it or change the law, and never lower a severity to quiet it.",
    "7. Commit `generated/` with the pages it describes.",
  ],
};

/** docs/cli.md §brief: what the writer does with a finding, which the maintainer's brief keeps. */
const WRITER_FINDINGS: readonly string[] = [
  "If a finding has `fix`, run its `argv` (fill any placeholders first). If it has",
  "`queue`, it is not yours — continue. A queued finding on a line you did not write",
  "is a warning, not a block.",
];

/**
 * docs/cli.md §brief: the "Findings" paragraph, one per role. A consumer runs no
 * writing verb, so its paragraph says whose a finding is rather than how to act on it.
 */
const FINDINGS: Readonly<Record<Role, readonly string[]>> = {
  consumer: [
    "A finding with `fix` names an argv a writer runs: report the finding and run nothing.",
    "A finding with `queue` is a judgment for a maintainer. A queued finding on a line you",
    "did not write is a warning, not a block.",
  ],
  writer: WRITER_FINDINGS,
  maintainer: WRITER_FINDINGS,
};

export interface BriefInput {
  role: Role;
  /**
   * The registry, PASSED rather than imported: `commands.ts` imports the brief
   * verb, so importing it back here is a cycle whose top-level constants read
   * `undefined` under ESM. The caller has the array; handing it over costs one
   * parameter and removes the cycle entirely.
   */
  commands: readonly CommandSpec[];
  registry: FlattenedRegistry;
  /**
   * docs/extending.md §What a module registers: the skill fragments the loaded
   * modules contributed. A kit's grammar is law an agent has to write under, and
   * a brief that did not say so would leave the agent to infer it from findings.
   */
  moduleSkills?: readonly { module: string; heading: string; body: string }[];
  /**
   * docs/constitution.md §Vocabularies: the census of every REGISTERED vocabulary, computed by the
   * caller's one parser pass — a kit's vocabulary is a vocabulary here too.
   */
  observed: Readonly<Record<string, readonly { label: string; count: number }[]>>;
  /**
   * docs/cli.md §The envelope: the law digest, the same one every vault verb's
   * `metadata.bundle.law` carries, so a brief can be told from the law it was
   * cut from.
   */
  lawDigest: string;
  /**
   * docs/constitution.md §exports: the export this brief is rendered for, when
   * it is one — its name and the bundle it was cut from — so a brief read in a
   * copy says which copy it is.
   */
  exportOf?: { name: string; bundle: string };
}

/**
 * docs/cli.md §brief: the modules' own paragraphs, in load order
 * and under the module that contributed each. Byte-reproducible like the rest of
 * the brief: the order is the registry's, and the registry's order is the
 * bundle's declaration order.
 */
function moduleSkillLines(
  fragments: readonly { module: string; heading: string; body: string }[],
): string[] {
  if (fragments.length === 0) return [];
  const out: string[] = ["## What the loaded modules add", ""];
  for (const fragment of fragments) {
    out.push(`### ${fragment.heading} (\`${fragment.module}\`)`, "", fragment.body, "");
  }
  return out;
}

/**
 * docs/cli.md §skills Byte-reproducible from the registry and the census:
 * no clock, no absolute path, no counts that change on a content commit except
 * the census block, which is why the LIVE counts live in `type show --brief`.
 */
export function renderBrief(input: BriefInput): string {
  const { role, registry } = input;
  const rank = ROLE_RANK[role];
  const verbs = input.commands
    .filter((c) => ROLE_RANK[c.role] <= rank)
    .sort((a, b) => codeUnitCompare(a.name, b.name));
  const types = [...registry.types.values()]
    .filter((t) => t.abstract !== true && t.status === "active")
    .sort((a, b) => codeUnitCompare(a.name, b.name));
  const reserved = ["claude", "agents", "readme", "skill", "index", "log"];
  // The table this bundle is judged under: the kernel's rows plus every arm
  // and check a loaded module registered, so the count is this vault's.
  const rows = passRows(registry.modules);
  const fixRouted = rows.filter((r) => r.fixer !== undefined).length;
  const vocabularies = [...registry.vocabularies.values()].sort((a, b) =>
    codeUnitCompare(a.name, b.name),
  );

  return [
    `# wikiwright — the ${role}'s brief`,
    "",
    "Generated by `wikiwright brief`. Do not edit: it is regenerated per install,",
    "and the judgment that is not in it lives in the hand-written skill beside it.",
    "",
    `Law digest: \`${input.lawDigest}\``,
    "",
    ...(input.exportOf === undefined
      ? []
      : [
          `Export: \`${input.exportOf.name}\`, a read-only copy of the bundle \`${input.exportOf.bundle}\`.`,
          "",
        ]),
    "## The loop",
    "",
    ...LOOPS[role],
    "",
    "## Findings",
    "",
    ...FINDINGS[role],
    "",
    `Of ${rows.length} passes, ${fixRouted} name a fixer; the rest are queues or census rows.`,
    "",
    "One sentence on search: not-found is only as good as the coverage block. Never",
    "claim absence while `caps.hit` is true — the cap cut the list before the end.",
    "",
    "## Verbs",
    "",
    ...verbs.flatMap(verbLine),
    "## Types",
    "",
    ...types.map(
      (t) => `- \`${t.name}\` — ${t.use_when ?? t.description ?? "no use_when declared"}`,
    ),
    "",
    "## Vocabularies, as declared",
    "",
    ...vocabularies.flatMap((v) => [`### \`${v.name}\` (${v.mode})`, "", ...declaredLines(v), ""]),
    "## Vocabularies, as this vault uses them",
    "",
    ...Object.entries(input.observed)
      .sort(([a], [b]) => codeUnitCompare(a, b))
      .flatMap(([name, rows]) => [`### \`${name}\``, "", ...observedLines(name, rows), ""]),
    ...moduleSkillLines(input.moduleSkills ?? []),
    "## Names",
    "",
    `Reserved basenames: ${reserved.map((r) => `\`${r}\``).join(", ")}.`,
    "",
    "A wikilink resolves to a canonical basename, never to an alias: write",
    "`[[Canonical|what you meant]]`. A page whose title is not Latin carries a Latin",
    "alias, so both scripts find it.",
    "",
  ].join("\n");
}

/**
 * The brief for a loaded law over a given page set. `briefFor` reads both off
 * the disk; `init` hands it the vault as it will stand AFTER the copy, so the
 * plan can say whether the installed brief would change (docs/cli.md §The dry-run law).
 * Over a copy, the header names the export its marker names, unless the
 * caller names one (the export renderer, for the copy it is about to write).
 */
export function briefOf(
  root: string,
  vault: VaultOk,
  pages: PageInput[],
  role: Role,
  commands: readonly CommandSpec[],
  exportOf?: { name: string; bundle: string },
  law?: string,
): string {
  const options = lintOptionsFor(vault, buildNameIndex(pages));
  // docs/constitution.md §Vocabularies: every vocabulary the loaded modules register,
  // never a literal name — a kit's vocabulary is a vocabulary here too.
  const observed = Object.fromEntries(
    vocabularyNames(vault.modules).map((name) => [
      name,
      observeVocabulary(name, pages, vault.registry, options).map((row) => ({
        label: row.label,
        count: row.count,
      })),
    ]),
  );
  return renderBrief({
    role,
    commands,
    registry: vault.registry,
    moduleSkills: vault.modules.skills,
    observed,
    // The texts this vault was loaded from and the modules it declares, so a
    // plan rendered before its files land (`init`) digests the law it will
    // carry; the same function the envelope's `bundle.law` comes from.
    // An export names the law of the bytes it carries (`law`), the one its
    // marker records.
    lawDigest:
      law ??
      lawDigest(root, vault.lawText.constitution, vault.lawText.engine, vault.engine.modules ?? []),
    ...exportHeader(root, exportOf),
  });
}

/** The export a brief's header names: the caller's, or the marker's at `root`. */
function exportHeader(
  root: string,
  exportOf: { name: string; bundle: string } | undefined,
): { exportOf?: { name: string; bundle: string } } {
  if (exportOf !== undefined) return { exportOf };
  const marker = markerAt(root);
  return marker.kind === "valid"
    ? { exportOf: { name: marker.marker.name, bundle: marker.marker.bundle } }
    : {};
}
